### PR TITLE
Count collection

### PR DESCRIPTION
**Pull request by chapeupreto**
Count all elements in a collection.

### CODE REVIEW

**Comment by gcds** [comment]
Don't you think this function is a bit overkill?

**Comment by chapeupreto** [comment]
I don't think so, since it uses same approach as http://php.net/count

**Comment by gcds** [comment]
No, I mean overkill to include wrapper for same name and some thing doing function

**Comment by chapeupreto** [comment]
Hm, I see. However, we need a way to count the elements in a collection. Which function name do you suggest? size() ? length() ?

**Comment by gcds** [comment]
No I mean do we really need this function and just dont use count?

**Comment by chapeupreto** [comment]
Since we are using this Collection namespace for a bunch of array related functions, I think there's no problem by using that. It is kind of the same idea used in Strings\length(). Maybe we should use another function name instead of count(), I dunno. What  do you say?

**Comment by gcds** [comment]
Then I think "size" would be better option... Because of Collection\size like String\length? What do you think?

**Comment by chapeupreto** [comment]
You're right. Give it a try now please.

**Comment by gcds** [comment]
Thanks for effort :+1: Merry Christmas and Happy New Year :gift: :tada:

**Comment by chapeupreto** [comment]
Thank you! Merry Xmas and happy new year for you and your beloved ones too. :bowtie: :+1: :gift:

**Pull request merged**
