### PR TITLE
Little optimization for some() function

### PR DESCRIPTION
**Pull request by zhikiri**
I think this solution can work better, we skip unnecessary iterations.

### CODE REVIEW

**Comment by gcds** [comment]
Please squash the commits to single commit according here https://github.com/phpfunct/funct/blob/master/CONTRIBUTING.md#sending-a-pull-request
Thank you :+1:

**Comment by zhikiri** [comment]
Please, check it out now

**Comment by gcds** [comment]
I think you forgot after rebase `git push --force` because I still see 3 commits. Merry Christmas and Happy New Year :tada:

**Comment by zhikiri** [comment]
Haa, yes, You was right )
Thanks, and Happy Holidays for you too

**Comment by gcds** [comment]
Thanks for effort have a nice holidays :+1:

**Pull request merged**
